GET http://localhost:3003/api/users

###

POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

{
    "username": "ken4",
    "name": "Ken Nguyen",
    "password": "123456"
}

###

POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

{
    "username": "ke",
    "name": "Ken Nguyen",
    "password": "123456"
}

