POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Ken Nguyen",
    "number": "s"
}

###

DELETE http://localhost:3001/api/persons/656e682839cab345f445bb61


###

GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/api/persons/656e682839cab345f445bb61

###
PUT  http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Ken Nguyen",
    "number": 23233434
}

###
GET http://localhost:3001/api/info